# Generated by Django 3.0.8 on 2020-07-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srpuser',
            name='host_password_verifier',
            field=models.BinaryField(max_length=200),
        ),
    ]
