# Generated by Django 3.0.8 on 2020-07-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200730_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SRPUser',
        ),
    ]
