# Generated by Django 3.0.8 on 2020-08-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_manager', '0003_auto_20200811_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidToken',
        ),
    ]
