#!/bin/bash

echo -e "Preparing...\n"

node $PWD/deepapi/app.js &
python $PWD/scripts/encrypt_decrypt_locally.py &&
killall node &&

export PYTHONPATH="$PWD/DEEPVAULT" &&
export TEMP='/tmp/'$(ls /tmp | grep '^[0-9a-f]*$') &&
# use the virtual python interpreter
python -c "from utils import fernet_keystore_utils; fernet_keystore_utils.generate_keystore(10)" &&
python -c "from utils import crypto_utils; crypto_utils.encrypt_keystore('$PWD/keystore.enc', '$TEMP')" &&

echo -e "Done.\n"
